module.exports = [
  'strapi::errors',
  'strapi::security',
  // 'strapi::cors',
  {
    name: "strapi::cors",
    config: {
      expose: [
        "WWW-Authenticate", 
        "Server-Authorization", 
        "Access-Control-Allow-Credentials",
        "Access-Control-Allow-Origin",
        "Access-Control-Expose-Headers",
        "Connection",
        "Content-Length",
        "Content-Security-Policy",
        "Content-Type",
        "Date",
        "Expect-CT",
        "Keep-Alive",
        "Referrer-Policy",
        "Server",
        "Strict-Transport-Security",
        "Vary",
        "X-Content-Type-Options",
        "X-DNS-Prefetch-Control",
        "X-Download-Options",
        "X-Frame-Options",
        "X-Permitted-Cross-Domain-Policies",
        "X-Powered-By",
      ]
    },
  },
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
];
