/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import awesomeHelp from "@exfabrica/strapi-plugin-awesome-help/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "awesome-help": awesomeHelp,
    i18n: i18N,
    "users-permissions": usersPermissions,
  },
});
